package com.fisi.sd.entity;
// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "sdtienda")
public class Cliente implements java.io.Serializable {

	private String vruc;
	private String vapellidoPaterno;
	private String vapellidoMaterno;
	private String vnombre;
	private String vtelefono;
	private String vcelular;
	private String vdireccion;
	private Set<Ordencompra> ordencompras = new HashSet<Ordencompra>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Cliente() {
	}

	public Cliente(String vruc) {
		this.vruc = vruc;
	}

	public Cliente(String vruc, String vapellidoPaterno, String vapellidoMaterno, String vnombre, String vtelefono,
			String vcelular, String vdireccion, Set ordencompras, Set usuarios) {
		this.vruc = vruc;
		this.vapellidoPaterno = vapellidoPaterno;
		this.vapellidoMaterno = vapellidoMaterno;
		this.vnombre = vnombre;
		this.vtelefono = vtelefono;
		this.vcelular = vcelular;
		this.vdireccion = vdireccion;
		this.ordencompras = ordencompras;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "vRUC", unique = true, nullable = false, length = 11)
	public String getVruc() {
		return this.vruc;
	}

	public void setVruc(String vruc) {
		this.vruc = vruc;
	}

	@Column(name = "vApellidoPaterno", length = 40)
	public String getVapellidoPaterno() {
		return this.vapellidoPaterno;
	}

	public void setVapellidoPaterno(String vapellidoPaterno) {
		this.vapellidoPaterno = vapellidoPaterno;
	}

	@Column(name = "vApellidoMaterno", length = 40)
	public String getVapellidoMaterno() {
		return this.vapellidoMaterno;
	}

	public void setVapellidoMaterno(String vapellidoMaterno) {
		this.vapellidoMaterno = vapellidoMaterno;
	}

	@Column(name = "vNombre", length = 40)
	public String getVnombre() {
		return this.vnombre;
	}

	public void setVnombre(String vnombre) {
		this.vnombre = vnombre;
	}

	@Column(name = "vTelefono", length = 7)
	public String getVtelefono() {
		return this.vtelefono;
	}

	public void setVtelefono(String vtelefono) {
		this.vtelefono = vtelefono;
	}

	@Column(name = "vCelular", length = 9)
	public String getVcelular() {
		return this.vcelular;
	}

	public void setVcelular(String vcelular) {
		this.vcelular = vcelular;
	}

	@Column(name = "vDireccion", length = 60)
	public String getVdireccion() {
		return this.vdireccion;
	}

	public void setVdireccion(String vdireccion) {
		this.vdireccion = vdireccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Ordencompra> getOrdencompras() {
		return this.ordencompras;
	}

	public void setOrdencompras(Set<Ordencompra> ordencompras) {
		this.ordencompras = ordencompras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
