package com.fisi.sd.entity;
// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "sdtienda")
public class Producto implements java.io.Serializable {

	private Integer vcodigo;
	private String vnombre;
	private String vdescripcion;
	private Double nprecioUnitario;
	private Integer ncantidad;
	private Set<OrdencompraHasProducto> ordencompraHasProductos = new HashSet<OrdencompraHasProducto>(0);

	public Producto() {
	}

	public Producto(String vnombre, String vdescripcion, Double nprecioUnitario, Integer ncantidad,
			Set ordencompraHasProductos) {
		this.vnombre = vnombre;
		this.vdescripcion = vdescripcion;
		this.nprecioUnitario = nprecioUnitario;
		this.ncantidad = ncantidad;
		this.ordencompraHasProductos = ordencompraHasProductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "vCodigo", unique = true, nullable = false)
	public Integer getVcodigo() {
		return this.vcodigo;
	}

	public void setVcodigo(Integer vcodigo) {
		this.vcodigo = vcodigo;
	}

	@Column(name = "vNombre", length = 40)
	public String getVnombre() {
		return this.vnombre;
	}

	public void setVnombre(String vnombre) {
		this.vnombre = vnombre;
	}

	@Column(name = "vDescripcion", length = 40)
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

	@Column(name = "nPrecioUnitario", precision = 22, scale = 0)
	public Double getNprecioUnitario() {
		return this.nprecioUnitario;
	}

	public void setNprecioUnitario(Double nprecioUnitario) {
		this.nprecioUnitario = nprecioUnitario;
	}

	@Column(name = "nCantidad")
	public Integer getNcantidad() {
		return this.ncantidad;
	}

	public void setNcantidad(Integer ncantidad) {
		this.ncantidad = ncantidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<OrdencompraHasProducto> getOrdencompraHasProductos() {
		return this.ordencompraHasProductos;
	}

	public void setOrdencompraHasProductos(Set<OrdencompraHasProducto> ordencompraHasProductos) {
		this.ordencompraHasProductos = ordencompraHasProductos;
	}

}
