package com.fisi.sd.entity;
// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trabajador generated by hbm2java
 */
@Entity
@Table(name = "trabajador", catalog = "sdtienda")
public class Trabajador implements java.io.Serializable {

	private String vdni;
	private String vapellidoPaterno;
	private String vapellidoMaterno;
	private String vnombre;
	private Integer ntipoTrabajador;

	public Trabajador() {
	}

	public Trabajador(String vdni) {
		this.vdni = vdni;
	}

	public Trabajador(String vdni, String vapellidoPaterno, String vapellidoMaterno, String vnombre,
			Integer ntipoTrabajador) {
		this.vdni = vdni;
		this.vapellidoPaterno = vapellidoPaterno;
		this.vapellidoMaterno = vapellidoMaterno;
		this.vnombre = vnombre;
		this.ntipoTrabajador = ntipoTrabajador;
	}

	@Id

	@Column(name = "vDNI", unique = true, nullable = false, length = 8)
	public String getVdni() {
		return this.vdni;
	}

	public void setVdni(String vdni) {
		this.vdni = vdni;
	}

	@Column(name = "vApellidoPaterno", length = 40)
	public String getVapellidoPaterno() {
		return this.vapellidoPaterno;
	}

	public void setVapellidoPaterno(String vapellidoPaterno) {
		this.vapellidoPaterno = vapellidoPaterno;
	}

	@Column(name = "vApellidoMaterno", length = 40)
	public String getVapellidoMaterno() {
		return this.vapellidoMaterno;
	}

	public void setVapellidoMaterno(String vapellidoMaterno) {
		this.vapellidoMaterno = vapellidoMaterno;
	}

	@Column(name = "vNombre", length = 40)
	public String getVnombre() {
		return this.vnombre;
	}

	public void setVnombre(String vnombre) {
		this.vnombre = vnombre;
	}

	@Column(name = "nTipoTrabajador")
	public Integer getNtipoTrabajador() {
		return this.ntipoTrabajador;
	}

	public void setNtipoTrabajador(Integer ntipoTrabajador) {
		this.ntipoTrabajador = ntipoTrabajador;
	}

}
