package com.fisi.sd.entity;
// Generated 22/11/2019 01:09:25 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "sdtienda")
public class Usuario implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String vidUsuario;
	private Cliente cliente;
	private String vclave;

	public Usuario() {
	}

	public Usuario(String vidUsuario, Cliente cliente) {
		this.vidUsuario = vidUsuario;
		this.cliente = cliente;
	}

	public Usuario(String vidUsuario, Cliente cliente, String vclave) {
		this.vidUsuario = vidUsuario;
		this.cliente = cliente;
		this.vclave = vclave;
	}

	@Id

	@Column(name = "vIdUsuario", unique = true, nullable = false, length = 20)
	public String getVidUsuario() {
		return this.vidUsuario;
	}

	public void setVidUsuario(String vidUsuario) {
		this.vidUsuario = vidUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_vRUC", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "vClave", length = 70)
	public String getVclave() {
		return this.vclave;
	}

	public void setVclave(String vclave) {
		this.vclave = vclave;
	}

}
